spring.application.name=inventory_management_system
server.port=${PORT:8080}

# Disable DB + JPA fully
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration