spring.application.name=inventory_management_system

# FULLY DISABLE DB + JPA
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# SERVER
server.port=${PORT:8080}